# Locate libcurllibrary
# This module defines
#  LIBCURL_FOUND, if false, do not try to link to libcurl
#  LIBCURL_LIBRARIES
#  LIBCURL_INCLUDE_DIRS, where to find curl.h

FIND_PATH(LIBCURL_INCLUDE_DIRS NAMES curl/curl.h HINTS ${LIBCURL_DIR}/include)
FIND_LIBRARY(LIBCURL_LIBRARIES NAMES curl libcurl HINTS ${LIBCURL_DIR}/Debug/lib ${LIBCURL_DIR}/lib ${LIBCURL_DIR})

# if(WIN32)
# endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCURL DEFAULT_MSG LIBCURL_LIBRARIES LIBCURL_INCLUDE_DIRS)

if(LIBCURL_FOUND AND NOT TARGET LIBCURL)
  add_library(curl UNKNOWN IMPORTED)
  set_target_properties(curl PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
	IMPORTED_LOCATION "${LIBCURL_LIBRARIES}"
	INTERFACE_LINK_LIBRARIES "${LIBCURL_LIBRARIES_WIN}"
	INTERFACE_INCLUDE_DIRECTORIES "${LIBCURL_INCLUDE_DIRS}"
	)
endif()
