# Locate libprotobuf3library
# This module defines
#  LIBPROTOBUF3_FOUND, if false, do not try to link to libprotobuf3
#  LIBPROTOBUF3_LIBRARIES
#  LIBPROTOBUF3_INCLUDE_DIRS, where to find protobuf3.h

FIND_PATH(LIBPROTOBUF3_INCLUDE_DIRS NAMES google/protobuf/type.proto HINTS ${LIBPROTOBUF3_DIR}/include)
FIND_LIBRARY(LIBPROTOBUF3_LIBRARIES NAMES protobuf HINTS ${LIBPROTOBUF3_DIR}/lib ${LIBPROTOBUF3_DIR})

# if(WIN32)
# endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBPROTOBUF3 DEFAULT_MSG LIBPROTOBUF3_LIBRARIES LIBPROTOBUF3_INCLUDE_DIRS)

if (LIBPROTOBUF3_FOUND AND NOT TARGET LIBPROTOBUF3)
    add_library(protobuf3 UNKNOWN IMPORTED)
    set_target_properties(protobuf3 PROPERTIES
            IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
            IMPORTED_LOCATION "${LIBPROTOBUF3_LIBRARIES}"
            INTERFACE_LINK_LIBRARIES "${LIBPROTOBUF3_LIBRARIES_WIN}"
            INTERFACE_INCLUDE_DIRECTORIES "${LIBPROTOBUF3_INCLUDE_DIRS}"
            )
else ()
    MESSAGE(FATAL_ERROR "Could not locate google-protobuf3")
endif ()
